/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick_find;

public class QF {

    private int[] ids;

    public QF (int n){
        this.ids = new int[n];

        for(int i = 0; i < n; i++){
            this.ids[i] = i;
        }
    }

    public boolean connected(int p, int q){
        return this.ids[p] == this.ids[q];
    }

    public void union(int p, int q){
        int pid = this.ids[p];
        int qid = this.ids[q];

        for(int i =0; i < this.ids.length; i++){
            if(this.ids[i] == pid){
                this.ids[i] = qid;
            }
        }
    }
}
